# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: martsblog
email: martin.stein@genode-labs.com
description: >
  A blog about OS development, outdoor activities, vegan lifestyle, the
  universe, and everything...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://m-stein.github.io" # the base hostname & protocol for your site
github_username: m-stein

# Build settings
markdown: kramdown
gems:
  - jemoji
